In [1]:
import numpy as np
X = np.genfromtxt("ionosphere.txt", delimiter=",")
X[:3]

array([[ 1.     ,  0.     ,  0.99539, -0.05889,  0.85243,  0.02306,
         0.83398, -0.37708,  1.     ,  0.0376 ,  0.85243, -0.17755,
         0.59755, -0.44945,  0.60536, -0.38223,  0.84356, -0.38542,
         0.58212, -0.32192,  0.56971, -0.29674,  0.36946, -0.47357,
         0.56811, -0.51171,  0.41078, -0.46168,  0.21266, -0.3409 ,
         0.42267, -0.54487,  0.18641, -0.453  ,  1.     ],
       [ 1.     ,  0.     ,  1.     , -0.18829,  0.93035, -0.36156,
        -0.10868, -0.93597,  1.     , -0.04549,  0.50874, -0.67743,
         0.34432, -0.69707, -0.51685, -0.97515,  0.05499, -0.62237,
         0.33109, -1.     , -0.13151, -0.453  , -0.18056, -0.35734,
        -0.20332, -0.26569, -0.20468, -0.18401, -0.1904 , -0.11593,
        -0.16626, -0.06288, -0.13738, -0.02447, -1.     ],
       [ 1.     ,  0.     ,  1.     , -0.03365,  1.     ,  0.00485,
         1.     , -0.12062,  0.88965,  0.01198,  0.73082,  0.05346,
         0.85443,  0.00827,  0.54591,  0.00299,  0.83775, -0.13644

In [2]:
X = np.genfromtxt("ionosphere.txt", delimiter=",",
                  usecols=np.arange(34))
X[:3]

array([[ 1.     ,  0.     ,  0.99539, -0.05889,  0.85243,  0.02306,
         0.83398, -0.37708,  1.     ,  0.0376 ,  0.85243, -0.17755,
         0.59755, -0.44945,  0.60536, -0.38223,  0.84356, -0.38542,
         0.58212, -0.32192,  0.56971, -0.29674,  0.36946, -0.47357,
         0.56811, -0.51171,  0.41078, -0.46168,  0.21266, -0.3409 ,
         0.42267, -0.54487,  0.18641, -0.453  ],
       [ 1.     ,  0.     ,  1.     , -0.18829,  0.93035, -0.36156,
        -0.10868, -0.93597,  1.     , -0.04549,  0.50874, -0.67743,
         0.34432, -0.69707, -0.51685, -0.97515,  0.05499, -0.62237,
         0.33109, -1.     , -0.13151, -0.453  , -0.18056, -0.35734,
        -0.20332, -0.26569, -0.20468, -0.18401, -0.1904 , -0.11593,
        -0.16626, -0.06288, -0.13738, -0.02447],
       [ 1.     ,  0.     ,  1.     , -0.03365,  1.     ,  0.00485,
         1.     , -0.12062,  0.88965,  0.01198,  0.73082,  0.05346,
         0.85443,  0.00827,  0.54591,  0.00299,  0.83775, -0.13644,
         0.75535, 

In [3]:
y = np.genfromtxt("ionosphere.txt", delimiter=",",
                  usecols=34, dtype='int')
y[:3]

array([ 1, -1,  1])

In [4]:
def cube(x):
    """this is my first function in this module; it cubes a number"""
    return x**3
cube(3)

27

In [5]:
help(cube)

Help on function cube in module __main__:

cube(x)
    this is my first function in this module; it cubes a number



In [6]:
def powers(x):
    """this function computes both square and cube"""
    return x**2, x**3
powers(3)

(9, 27)

In [7]:
powers(3)[1]

27

In [8]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [9]:
b = a
b

array([1, 2, 3])

In [10]:
a[1] = 100
a

array([  1, 100,   3])

In [11]:
b

array([  1, 100,   3])

In [12]:
b = np.array(a)

In [13]:
b = a.copy()

In [14]:
a = np.array([1,2,3])
b = np.array([5,6])
np.concatenate((a,b))

array([1, 2, 3, 5, 6])

In [15]:
my_array = np.concatenate((np.arange(10**6),np.array([4])))